name: quit_mate
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  #cache
  uuid: ^4.2.2
  shared_preferences: ^2.2.1
  build_runner: ^2.4.6
  #network
  connectivity_plus: ^5.0.2
  dio: ^5.3.3
  json_serializable: ^6.7.1
  #state manage
  flutter_riverpod: ^2.4.0
  #firebase
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3
  #test
  path_provider: ^2.1.1
  #language
  easy_localization: ^3.0.3
  #material
  cupertino_icons: ^1.0.2
  lottie: ^2.6.0
  flutter_svg: ^2.0.7
  percent_indicator: ^4.2.3
  fl_chart: ^0.65.0
  intl: ^0.18.1
  flutter_datetime_picker: ^1.5.1
  numberpicker: ^2.1.2
  smooth_page_indicator: ^1.1.0
  #notification
  awesome_notifications: ^0.8.2
  rename_app: ^1.3.1
  #test
  mockito: ^5.4.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/translations/
    - assets/svg/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
