import 'dart:math';
import 'package:quit_mate/src/feature/affirmation/model/affirmations.dart';

class GetRandomAffirmation {
  String getRandomAffirmation() {
    final List<String> affirmationsList = [
      Affirmations.affirmation1,
      Affirmations.affirmation2,
      Affirmations.affirmation3,
      Affirmations.affirmation4,
      Affirmations.affirmation5,
      Affirmations.affirmation6,
      Affirmations.affirmation7,
      Affirmations.affirmation8,
      Affirmations.affirmation9,
      Affirmations.affirmation10,
      Affirmations.affirmation11,
      Affirmations.affirmation12,
      Affirmations.affirmation13,
      Affirmations.affirmation14,
      Affirmations.affirmation15,
      Affirmations.affirmation16,
      Affirmations.affirmation17,
      Affirmations.affirmation18,
      Affirmations.affirmation19,
      Affirmations.affirmation20,
      Affirmations.affirmation21,
      Affirmations.affirmation22,
      Affirmations.affirmation23,
      Affirmations.affirmation24,
      Affirmations.affirmation25,
      Affirmations.affirmation26,
      Affirmations.affirmation27,
      Affirmations.affirmation28,
      Affirmations.affirmation29,
      Affirmations.affirmation30,
      Affirmations.affirmation31,
      Affirmations.affirmation32,
      Affirmations.affirmation33,
      Affirmations.affirmation34,
      Affirmations.affirmation35,
      Affirmations.affirmation36,
      Affirmations.affirmation37,
      Affirmations.affirmation38,
      Affirmations.affirmation39,
      Affirmations.affirmation40,
      Affirmations.affirmation41,
      Affirmations.affirmation42,
      Affirmations.affirmation43,
      Affirmations.affirmation44,
      Affirmations.affirmation45,
      Affirmations.affirmation46,
      Affirmations.affirmation47,
      Affirmations.affirmation48,
      Affirmations.affirmation49,
      Affirmations.affirmation50,
      Affirmations.affirmation51,
      Affirmations.affirmation52,
      Affirmations.affirmation53,
      Affirmations.affirmation54,
      Affirmations.affirmation55,
      Affirmations.affirmation56,
      Affirmations.affirmation57,
      Affirmations.affirmation58,
      Affirmations.affirmation59,
      Affirmations.affirmation60,
      Affirmations.affirmation61,
      Affirmations.affirmation62,
      Affirmations.affirmation63,
      Affirmations.affirmation64,
      Affirmations.affirmation65,
      Affirmations.affirmation66,
      Affirmations.affirmation67,
      Affirmations.affirmation68,
      Affirmations.affirmation69,
      Affirmations.affirmation70,
      Affirmations.affirmation71,
      Affirmations.affirmation72,
      Affirmations.affirmation73,
      Affirmations.affirmation74,
      Affirmations.affirmation75,
      Affirmations.affirmation76,
      Affirmations.affirmation77,
      Affirmations.affirmation78,
      Affirmations.affirmation79,
      Affirmations.affirmation80,
      Affirmations.affirmation81,
      Affirmations.affirmation82,
      Affirmations.affirmation83,
      Affirmations.affirmation84,
      Affirmations.affirmation85,
      Affirmations.affirmation86,
      Affirmations.affirmation87,
      Affirmations.affirmation88,
      Affirmations.affirmation89,
      Affirmations.affirmation90,
      Affirmations.affirmation91,
      Affirmations.affirmation92,
      Affirmations.affirmation93,
      Affirmations.affirmation94,
      Affirmations.affirmation95,
      Affirmations.affirmation96,
      Affirmations.affirmation97,
      Affirmations.affirmation98,
      Affirmations.affirmation99,
    ];

    final random = Random();
    final randomIndex = random.nextInt(affirmationsList.length);

    return affirmationsList[randomIndex];
  }
}
