class AddictiveFactor {
  final List<String> addictiveFactorList = [
    "Alcohol",
    "Adderall",
    "Amphetamines",
    "Beer",
    "Benzodiazepines",
    "Binge Drinking",
    "Binge Eating",
    "Binging & Purging",
    "Booze",
    "Bourbon",
    "Bread",
    "Caffeine",
    "Cigarettes",
    "Cocaine",
    "Cookies",
    "Dextromethorphan (DXM)",
    "Drugs",
    "Eating Disorder",
    "Eating Disorder (under eating)",
    "Ecstasy",
    "Energy Drinks",
    "Fast Food",
    "Fentanyl",
    "Food Restricting",
    "Gambling",
    "Gin",
    "Gluten",
    "Hair Pulling",
    "Heroin",
    "Internet",
    "Junk Food",
    "Ketamine",
    "Kratom",
    "Marijuana",
    "Masturbation",
    "Meat & Dairy",
    "Meth",
    "Methadone",
    "Nail Biting",
    "Nicotine",
    "Online Shopping",
    "Opiates",
    "Pills",
    "Pornography",
    "Purging",
    "Rum",
    "Self-harm",
    "Sex",
    "Skin Picking",
    "Social Media",
    "Soft Drinks",
    "Suboxone",
    "Sugar",
    "Sweets",
    "Tequila",
    "Tobacco",
    "Vaping",
    "Video Games",
    "Vodka",
    "Whiskey",
    "Wine",
    "Xanax"
  ];
}
